# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AI
                                 A QGIS plugin
 一款智能辅助设计插件
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-19
        copyright            : (C) 2026 by zsz
        email                : 15098922607@163.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AI class from file AI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .AI_Studio import AI
    return AI(iface)
